# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'impedance_spectroscopy.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QHBoxLayout, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QProgressBar, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QTabWidget, QTextBrowser,
    QToolButton, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1364, 891)
        font = QFont()
        font.setFamilies([u"Courier 10 Pitch"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"../.designer/backup/pollo.jpg", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(120, 120))
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_13 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.tabWidget = QTabWidget(self.frame)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(440, 510))
        self.tabWidget.setMaximumSize(QSize(16777215, 16777215))
        self.tabWidget.setAcceptDrops(False)
        self.datos = QWidget()
        self.datos.setObjectName(u"datos")
        self.frame_3 = QFrame(self.datos)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(-1, 430, 631, 381))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget_2 = QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(10, 30, 611, 351))
        self.mpl_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.mpl_2.setObjectName(u"mpl_2")
        self.mpl_2.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.datos)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(240, 424, 171, 31))
        font1 = QFont()
        font1.setFamilies([u"Courier 10 Pitch"])
        font1.setPointSize(12)
        font1.setBold(False)
        self.label_4.setFont(font1)
        self.label_3 = QLabel(self.datos)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(240, 10, 141, 31))
        self.label_3.setFont(font1)
        self.frame_2 = QFrame(self.datos)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 10, 631, 401))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget = QWidget(self.frame_2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 30, 611, 371))
        self.mpl_1 = QVBoxLayout(self.verticalLayoutWidget)
        self.mpl_1.setObjectName(u"mpl_1")
        self.mpl_1.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.datos)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(650, 10, 401, 21))
        font2 = QFont()
        font2.setFamilies([u"Sans"])
        font2.setPointSize(15)
        font2.setBold(True)
        self.label.setFont(font2)
        self.frame_4 = QFrame(self.datos)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(650, 50, 441, 770))
        self.frame_4.setMinimumSize(QSize(0, 0))
        self.frame_4.setMaximumSize(QSize(441, 770))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.groupBox_13 = QGroupBox(self.frame_4)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 6, 421, 301))
        self.groupBox_13.setAutoFillBackground(False)
        self.f_inicial = QLineEdit(self.groupBox_13)
        self.f_inicial.setObjectName(u"f_inicial")
        self.f_inicial.setGeometry(QRect(130, 30, 71, 20))
        self.f_inicial.setReadOnly(False)
        self.n_puntos = QLineEdit(self.groupBox_13)
        self.n_puntos.setObjectName(u"n_puntos")
        self.n_puntos.setGeometry(QRect(130, 70, 71, 20))
        self.n_puntos.setReadOnly(False)
        self.label_42 = QLabel(self.groupBox_13)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(20, 60, 101, 20))
        font3 = QFont()
        font3.setFamilies([u"Courier 10 Pitch"])
        font3.setPointSize(9)
        self.label_42.setFont(font3)
        self.label_44 = QLabel(self.groupBox_13)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 30, 101, 16))
        self.label_44.setFont(font3)
        self.label_46 = QLabel(self.groupBox_13)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(30, 160, 91, 16))
        self.label_46.setFont(font3)
        self.f_final = QLineEdit(self.groupBox_13)
        self.f_final.setObjectName(u"f_final")
        self.f_final.setGeometry(QRect(130, 160, 71, 20))
        self.f_final.setReadOnly(False)
        self.label_43 = QLabel(self.groupBox_13)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(240, 20, 101, 20))
        self.label_43.setFont(font3)
        self.shunt = QLineEdit(self.groupBox_13)
        self.shunt.setObjectName(u"shunt")
        self.shunt.setGeometry(QRect(330, 30, 71, 20))
        self.shunt.setReadOnly(False)
        self.label_50 = QLabel(self.groupBox_13)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(40, 80, 101, 20))
        self.label_50.setFont(font3)
        self.label_51 = QLabel(self.groupBox_13)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(260, 40, 41, 20))
        self.label_51.setFont(font3)
        self.label_52 = QLabel(self.groupBox_13)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(40, 130, 101, 20))
        self.label_52.setFont(font3)
        self.label_53 = QLabel(self.groupBox_13)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(20, 110, 101, 20))
        self.label_53.setFont(font3)
        self.vosc = QLineEdit(self.groupBox_13)
        self.vosc.setObjectName(u"vosc")
        self.vosc.setGeometry(QRect(130, 120, 71, 20))
        self.vosc.setReadOnly(False)
        self.groupBox = QGroupBox(self.groupBox_13)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(240, 70, 161, 80))
        self.radioButton_lineal = QRadioButton(self.groupBox)
        self.radioButton_lineal.setObjectName(u"radioButton_lineal")
        self.radioButton_lineal.setGeometry(QRect(20, 27, 111, 23))
        self.radioButton_log = QRadioButton(self.groupBox)
        self.radioButton_log.setObjectName(u"radioButton_log")
        self.radioButton_log.setGeometry(QRect(20, 50, 111, 23))
        self.groupBox_3 = QGroupBox(self.groupBox_13)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(230, 160, 171, 131))
        self.groupBox_3.setCheckable(False)
        self.radioButton_DC_ON = QRadioButton(self.groupBox_3)
        self.radioButton_DC_ON.setObjectName(u"radioButton_DC_ON")
        self.radioButton_DC_ON.setGeometry(QRect(20, 27, 111, 23))
        self.label_15 = QLabel(self.groupBox_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 50, 141, 20))
        self.label_15.setFont(font3)
        self.nivel_DC = QLineEdit(self.groupBox_3)
        self.nivel_DC.setObjectName(u"nivel_DC")
        self.nivel_DC.setGeometry(QRect(50, 70, 71, 20))
        self.nivel_DC.setReadOnly(False)
        self.radioButton_DC_OFF = QRadioButton(self.groupBox_3)
        self.radioButton_DC_OFF.setObjectName(u"radioButton_DC_OFF")
        self.radioButton_DC_OFF.setGeometry(QRect(20, 90, 121, 21))
        self.groupBox_4 = QGroupBox(self.groupBox_13)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 200, 201, 91))
        self.radioButton_Corre = QRadioButton(self.groupBox_4)
        self.radioButton_Corre.setObjectName(u"radioButton_Corre")
        self.radioButton_Corre.setGeometry(QRect(20, 20, 111, 17))
        self.radioButton_F_Corre = QRadioButton(self.groupBox_4)
        self.radioButton_F_Corre.setObjectName(u"radioButton_F_Corre")
        self.radioButton_F_Corre.setGeometry(QRect(20, 40, 151, 17))
        self.n_ciclos = QLineEdit(self.groupBox_4)
        self.n_ciclos.setObjectName(u"n_ciclos")
        self.n_ciclos.setGeometry(QRect(120, 60, 71, 20))
        self.n_ciclos.setReadOnly(False)
        self.label_58 = QLabel(self.groupBox_4)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(0, 60, 121, 16))
        self.label_58.setFont(font3)
        self.MEDIR = QPushButton(self.frame_4)
        self.MEDIR.setObjectName(u"MEDIR")
        self.MEDIR.setGeometry(QRect(160, 470, 271, 41))
        font4 = QFont()
        font4.setFamilies([u"Courier New"])
        font4.setPointSize(14)
        font4.setBold(True)
        self.MEDIR.setFont(font4)
        self.groupBox_2 = QGroupBox(self.frame_4)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 310, 131, 261))
        self.comboBox_trazaA = QComboBox(self.groupBox_2)
        self.comboBox_trazaA.setObjectName(u"comboBox_trazaA")
        self.comboBox_trazaA.setGeometry(QRect(20, 47, 91, 21))
        self.comboBox_trazaA.setMaxVisibleItems(6)
        self.comboBox_trazaB = QComboBox(self.groupBox_2)
        self.comboBox_trazaB.setObjectName(u"comboBox_trazaB")
        self.comboBox_trazaB.setGeometry(QRect(20, 98, 91, 21))
        self.comboBox_trazaB.setMaxVisibleItems(6)
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 24, 101, 20))
        self.label_16.setFont(font3)
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 74, 101, 20))
        self.label_17.setFont(font3)
        self.REDRAW_MEASURE = QPushButton(self.groupBox_2)
        self.REDRAW_MEASURE.setObjectName(u"REDRAW_MEASURE")
        self.REDRAW_MEASURE.setGeometry(QRect(10, 130, 111, 41))
        self.SMOOTH_ON = QRadioButton(self.groupBox_2)
        self.SMOOTH_ON.setObjectName(u"SMOOTH_ON")
        self.SMOOTH_ON.setGeometry(QRect(10, 180, 111, 20))
        self.SMOOTH_OFF = QRadioButton(self.groupBox_2)
        self.SMOOTH_OFF.setObjectName(u"SMOOTH_OFF")
        self.SMOOTH_OFF.setGeometry(QRect(10, 240, 111, 20))
        self.k_factor = QLineEdit(self.groupBox_2)
        self.k_factor.setObjectName(u"k_factor")
        self.k_factor.setGeometry(QRect(40, 220, 41, 16))
        self.k_factor.setReadOnly(False)
        self.label_60 = QLabel(self.groupBox_2)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(10, 200, 121, 16))
        self.label_60.setFont(font3)
        self.textBrowser = QTextBrowser(self.frame_4)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 580, 421, 181))
        self.groupBox_18 = QGroupBox(self.frame_4)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(160, 310, 271, 151))
        self.LOAD_M = QPushButton(self.groupBox_18)
        self.LOAD_M.setObjectName(u"LOAD_M")
        self.LOAD_M.setGeometry(QRect(10, 30, 241, 21))
        self.toolButton_load = QToolButton(self.groupBox_18)
        self.toolButton_load.setObjectName(u"toolButton_load")
        self.toolButton_load.setGeometry(QRect(220, 60, 31, 21))
        self.load_path = QLineEdit(self.groupBox_18)
        self.load_path.setObjectName(u"load_path")
        self.load_path.setGeometry(QRect(10, 60, 201, 20))
        self.load_path.setReadOnly(False)
        self.SAVE_M = QPushButton(self.groupBox_18)
        self.SAVE_M.setObjectName(u"SAVE_M")
        self.SAVE_M.setGeometry(QRect(10, 90, 241, 21))
        self.toolButton_save = QToolButton(self.groupBox_18)
        self.toolButton_save.setObjectName(u"toolButton_save")
        self.toolButton_save.setGeometry(QRect(220, 120, 31, 21))
        self.save_path = QLineEdit(self.groupBox_18)
        self.save_path.setObjectName(u"save_path")
        self.save_path.setGeometry(QRect(10, 120, 201, 20))
        self.save_path.setReadOnly(False)
        self.progressBar = QProgressBar(self.frame_4)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(160, 540, 311, 23))
        self.progressBar.setValue(24)
        self.SAVE_cfg = QPushButton(self.datos)
        self.SAVE_cfg.setObjectName(u"SAVE_cfg")
        self.SAVE_cfg.setGeometry(QRect(1110, 50, 161, 41))
        self.last_medida = QLCDNumber(self.datos)
        self.last_medida.setObjectName(u"last_medida")
        self.last_medida.setGeometry(QRect(1140, 280, 91, 61))
        font5 = QFont()
        font5.setFamilies([u"Sans"])
        font5.setPointSize(10)
        font5.setBold(True)
        self.last_medida.setFont(font5)
        self.last_medida.setLineWidth(1)
        self.last_medida.setDigitCount(2)
        self.last_pollo = QLCDNumber(self.datos)
        self.last_pollo.setObjectName(u"last_pollo")
        self.last_pollo.setGeometry(QRect(1140, 160, 91, 61))
        self.last_pollo.setFont(font5)
        self.last_pollo.setLineWidth(1)
        self.last_pollo.setDigitCount(2)
        self.SAVE_DB = QPushButton(self.datos)
        self.SAVE_DB.setObjectName(u"SAVE_DB")
        self.SAVE_DB.setGeometry(QRect(1100, 380, 171, 61))
        self.load_path_db = QLineEdit(self.datos)
        self.load_path_db.setObjectName(u"load_path_db")
        self.load_path_db.setGeometry(QRect(1100, 670, 181, 20))
        self.load_path_db.setReadOnly(False)
        self.toolButton_load_db = QToolButton(self.datos)
        self.toolButton_load_db.setObjectName(u"toolButton_load_db")
        self.toolButton_load_db.setGeometry(QRect(1100, 700, 31, 21))
        self.spinBox_pollo_db = QSpinBox(self.datos)
        self.spinBox_pollo_db.setObjectName(u"spinBox_pollo_db")
        self.spinBox_pollo_db.setGeometry(QRect(1100, 479, 61, 41))
        font6 = QFont()
        font6.setFamilies([u"Sans"])
        font6.setPointSize(18)
        font6.setBold(True)
        self.spinBox_pollo_db.setFont(font6)
        self.spinBox_medida_db = QSpinBox(self.datos)
        self.spinBox_medida_db.setObjectName(u"spinBox_medida_db")
        self.spinBox_medida_db.setGeometry(QRect(1210, 479, 61, 41))
        self.spinBox_medida_db.setFont(font6)
        self.spinBox_medida_db.setMaximum(19)
        self.label_36 = QLabel(self.datos)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(1100, 640, 171, 20))
        font7 = QFont()
        font7.setFamilies([u"Sans"])
        font7.setPointSize(12)
        font7.setBold(True)
        self.label_36.setFont(font7)
        self.label_37 = QLabel(self.datos)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(1120, 130, 141, 20))
        font8 = QFont()
        font8.setFamilies([u"MS Shell Dlg 2"])
        font8.setPointSize(11)
        self.label_37.setFont(font8)
        self.label_38 = QLabel(self.datos)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(1120, 250, 151, 20))
        self.label_38.setFont(font8)
        self.label_39 = QLabel(self.datos)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(1100, 459, 71, 20))
        font9 = QFont()
        font9.setFamilies([u"MS Shell Dlg 2"])
        font9.setPointSize(10)
        font9.setBold(True)
        self.label_39.setFont(font9)
        self.label_40 = QLabel(self.datos)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(1200, 459, 71, 20))
        self.label_40.setFont(font9)
        self.spinBox_pollo_db_2 = QSpinBox(self.datos)
        self.spinBox_pollo_db_2.setObjectName(u"spinBox_pollo_db_2")
        self.spinBox_pollo_db_2.setGeometry(QRect(1156, 550, 61, 41))
        self.spinBox_pollo_db_2.setFont(font6)
        self.spinBox_pollo_db_2.setMinimum(0)
        self.spinBox_pollo_db_2.setMaximum(99)
        self.label_41 = QLabel(self.datos)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(1140, 530, 81, 20))
        font10 = QFont()
        font10.setFamilies([u"Sans"])
        font10.setPointSize(11)
        font10.setBold(True)
        self.label_41.setFont(font10)
        self.tabWidget.addTab(self.datos, "")
        self.calibracion = QWidget()
        self.calibracion.setObjectName(u"calibracion")
        self.calibracion.setAcceptDrops(False)
        self.GO_CAL = QPushButton(self.calibracion)
        self.GO_CAL.setObjectName(u"GO_CAL")
        self.GO_CAL.setGeometry(QRect(60, 230, 241, 71))
        font11 = QFont()
        font11.setFamilies([u"Courier 10 Pitch"])
        font11.setPointSize(12)
        font11.setBold(True)
        self.GO_CAL.setFont(font11)
        self.SAVE_CAL = QPushButton(self.calibracion)
        self.SAVE_CAL.setObjectName(u"SAVE_CAL")
        self.SAVE_CAL.setGeometry(QRect(340, 160, 171, 31))
        self.SAVE_CAL.setFont(font)
        self.groupBox_5 = QGroupBox(self.calibracion)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(60, 30, 241, 171))
        self.radioButton_config_cal_2 = QRadioButton(self.groupBox_5)
        self.radioButton_config_cal_2.setObjectName(u"radioButton_config_cal_2")
        self.radioButton_config_cal_2.setGeometry(QRect(20, 140, 161, 23))
        self.radioButton_config_cal_1 = QRadioButton(self.groupBox_5)
        self.radioButton_config_cal_1.setObjectName(u"radioButton_config_cal_1")
        self.radioButton_config_cal_1.setGeometry(QRect(20, 40, 201, 23))
        self.label_18 = QLabel(self.groupBox_5)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(40, 70, 91, 20))
        self.label_18.setFont(font3)
        self.c_load = QLineEdit(self.groupBox_5)
        self.c_load.setObjectName(u"c_load")
        self.c_load.setGeometry(QRect(130, 70, 71, 20))
        self.c_load.setReadOnly(False)
        self.label_19 = QLabel(self.groupBox_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 100, 81, 20))
        self.label_19.setFont(font3)
        self.g_load = QLineEdit(self.groupBox_5)
        self.g_load.setObjectName(u"g_load")
        self.g_load.setGeometry(QRect(130, 100, 71, 20))
        self.g_load.setReadOnly(False)
        self.groupBox_6 = QGroupBox(self.calibracion)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(340, 30, 221, 111))
        self.radioButton_pto_cal_usuario = QRadioButton(self.groupBox_6)
        self.radioButton_pto_cal_usuario.setObjectName(u"radioButton_pto_cal_usuario")
        self.radioButton_pto_cal_usuario.setGeometry(QRect(20, 70, 161, 23))
        self.radioButton_pto_cal_medidor = QRadioButton(self.groupBox_6)
        self.radioButton_pto_cal_medidor.setObjectName(u"radioButton_pto_cal_medidor")
        self.radioButton_pto_cal_medidor.setGeometry(QRect(20, 40, 131, 23))
        self.LOAD_CAL = QPushButton(self.calibracion)
        self.LOAD_CAL.setObjectName(u"LOAD_CAL")
        self.LOAD_CAL.setGeometry(QRect(340, 240, 171, 31))
        self.LOAD_CAL.setFont(font)
        self.toolButton_load_2 = QToolButton(self.calibracion)
        self.toolButton_load_2.setObjectName(u"toolButton_load_2")
        self.toolButton_load_2.setGeometry(QRect(520, 250, 31, 21))
        self.load_path_2 = QLineEdit(self.calibracion)
        self.load_path_2.setObjectName(u"load_path_2")
        self.load_path_2.setGeometry(QRect(340, 280, 211, 20))
        self.load_path_2.setReadOnly(False)
        self.save_path_2 = QLineEdit(self.calibracion)
        self.save_path_2.setObjectName(u"save_path_2")
        self.save_path_2.setGeometry(QRect(340, 200, 211, 21))
        self.toolButton_save_2 = QToolButton(self.calibracion)
        self.toolButton_save_2.setObjectName(u"toolButton_save_2")
        self.toolButton_save_2.setGeometry(QRect(520, 170, 31, 21))
        self.textBrowser_2 = QTextBrowser(self.calibracion)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(650, 50, 521, 471))
        self.groupBox_14 = QGroupBox(self.calibracion)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(60, 370, 431, 391))
        self.groupBox_14.setAutoFillBackground(False)
        self.f_inicial_2 = QLineEdit(self.groupBox_14)
        self.f_inicial_2.setObjectName(u"f_inicial_2")
        self.f_inicial_2.setGeometry(QRect(130, 50, 71, 20))
        self.f_inicial_2.setReadOnly(False)
        self.n_puntos_2 = QLineEdit(self.groupBox_14)
        self.n_puntos_2.setObjectName(u"n_puntos_2")
        self.n_puntos_2.setGeometry(QRect(130, 100, 71, 20))
        self.n_puntos_2.setReadOnly(False)
        self.label_45 = QLabel(self.groupBox_14)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(20, 90, 101, 20))
        self.label_45.setFont(font3)
        self.label_47 = QLabel(self.groupBox_14)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(20, 50, 101, 16))
        self.label_47.setFont(font3)
        self.label_48 = QLabel(self.groupBox_14)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(240, 50, 91, 16))
        self.label_48.setFont(font3)
        self.f_final_2 = QLineEdit(self.groupBox_14)
        self.f_final_2.setObjectName(u"f_final_2")
        self.f_final_2.setGeometry(QRect(330, 50, 71, 20))
        self.f_final_2.setReadOnly(False)
        self.label_49 = QLabel(self.groupBox_14)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(240, 90, 101, 20))
        self.label_49.setFont(font3)
        self.shunt_2 = QLineEdit(self.groupBox_14)
        self.shunt_2.setObjectName(u"shunt_2")
        self.shunt_2.setGeometry(QRect(330, 100, 71, 20))
        self.shunt_2.setReadOnly(False)
        self.label_54 = QLabel(self.groupBox_14)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(40, 110, 101, 20))
        self.label_54.setFont(font3)
        self.label_55 = QLabel(self.groupBox_14)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(260, 110, 41, 20))
        self.label_55.setFont(font3)
        self.label_56 = QLabel(self.groupBox_14)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(40, 184, 101, 20))
        self.label_56.setFont(font3)
        self.label_57 = QLabel(self.groupBox_14)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(20, 164, 101, 20))
        self.label_57.setFont(font3)
        self.vosc_2 = QLineEdit(self.groupBox_14)
        self.vosc_2.setObjectName(u"vosc_2")
        self.vosc_2.setGeometry(QRect(130, 170, 71, 20))
        self.vosc_2.setReadOnly(False)
        self.groupBox_8 = QGroupBox(self.groupBox_14)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(240, 150, 161, 80))
        self.radioButton_lineal_2 = QRadioButton(self.groupBox_8)
        self.radioButton_lineal_2.setObjectName(u"radioButton_lineal_2")
        self.radioButton_lineal_2.setGeometry(QRect(20, 27, 111, 23))
        self.radioButton_log_2 = QRadioButton(self.groupBox_8)
        self.radioButton_log_2.setObjectName(u"radioButton_log_2")
        self.radioButton_log_2.setGeometry(QRect(20, 50, 111, 23))
        self.groupBox_9 = QGroupBox(self.groupBox_14)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(20, 240, 171, 131))
        self.groupBox_9.setCheckable(False)
        self.radioButton_DC_OFF_2 = QRadioButton(self.groupBox_9)
        self.radioButton_DC_OFF_2.setObjectName(u"radioButton_DC_OFF_2")
        self.radioButton_DC_OFF_2.setGeometry(QRect(20, 50, 111, 23))
        self.radioButton_DC_ON_2 = QRadioButton(self.groupBox_9)
        self.radioButton_DC_ON_2.setObjectName(u"radioButton_DC_ON_2")
        self.radioButton_DC_ON_2.setGeometry(QRect(20, 27, 111, 23))
        self.label_21 = QLabel(self.groupBox_9)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 76, 141, 20))
        self.label_21.setFont(font3)
        self.nivel_DC_2 = QLineEdit(self.groupBox_9)
        self.nivel_DC_2.setObjectName(u"nivel_DC_2")
        self.nivel_DC_2.setGeometry(QRect(40, 100, 71, 20))
        self.nivel_DC_2.setReadOnly(False)
        self.groupBox_7 = QGroupBox(self.groupBox_14)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(220, 250, 181, 121))
        self.radioButton_Corre_2 = QRadioButton(self.groupBox_7)
        self.radioButton_Corre_2.setObjectName(u"radioButton_Corre_2")
        self.radioButton_Corre_2.setGeometry(QRect(20, 20, 111, 21))
        self.radioButton_F_Corre_2 = QRadioButton(self.groupBox_7)
        self.radioButton_F_Corre_2.setObjectName(u"radioButton_F_Corre_2")
        self.radioButton_F_Corre_2.setGeometry(QRect(20, 40, 151, 21))
        self.label_59 = QLabel(self.groupBox_7)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(0, 80, 121, 16))
        self.label_59.setFont(font3)
        self.n_ciclos_2 = QLineEdit(self.groupBox_7)
        self.n_ciclos_2.setObjectName(u"n_ciclos_2")
        self.n_ciclos_2.setGeometry(QRect(120, 80, 41, 20))
        self.n_ciclos_2.setReadOnly(False)
        self.tabWidget.addTab(self.calibracion, "")
        self.analisis = QWidget()
        self.analisis.setObjectName(u"analisis")
        self.frame_14 = QFrame(self.analisis)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(20, 20, 1261, 511))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget_11 = QWidget(self.frame_14)
        self.verticalLayoutWidget_11.setObjectName(u"verticalLayoutWidget_11")
        self.verticalLayoutWidget_11.setGeometry(QRect(0, 10, 921, 481))
        self.mpl_4 = QVBoxLayout(self.verticalLayoutWidget_11)
        self.mpl_4.setObjectName(u"mpl_4")
        self.mpl_4.setContentsMargins(0, 0, 0, 0)
        self.groupBox_60 = QGroupBox(self.frame_14)
        self.groupBox_60.setObjectName(u"groupBox_60")
        self.groupBox_60.setGeometry(QRect(940, 0, 271, 491))
        self.load_path_17 = QLineEdit(self.groupBox_60)
        self.load_path_17.setObjectName(u"load_path_17")
        self.load_path_17.setGeometry(QRect(10, 30, 211, 20))
        self.load_path_17.setReadOnly(False)
        self.toolButton_load_17 = QToolButton(self.groupBox_60)
        self.toolButton_load_17.setObjectName(u"toolButton_load_17")
        self.toolButton_load_17.setGeometry(QRect(230, 30, 31, 21))
        self.spinBox_pollo_6 = QSpinBox(self.groupBox_60)
        self.spinBox_pollo_6.setObjectName(u"spinBox_pollo_6")
        self.spinBox_pollo_6.setGeometry(QRect(73, 60, 51, 26))
        self.spinBox_pollo_6.setMaximum(9999)
        self.label_167 = QLabel(self.groupBox_60)
        self.label_167.setObjectName(u"label_167")
        self.label_167.setGeometry(QRect(10, 60, 67, 21))
        self.label_168 = QLabel(self.groupBox_60)
        self.label_168.setObjectName(u"label_168")
        self.label_168.setGeometry(QRect(150, 60, 67, 17))
        self.spinBox_medida_6 = QSpinBox(self.groupBox_60)
        self.spinBox_medida_6.setObjectName(u"spinBox_medida_6")
        self.spinBox_medida_6.setGeometry(QRect(203, 60, 61, 26))
        self.spinBox_medida_6.setMaximum(9999)
        self.VER_ANALISIS = QPushButton(self.groupBox_60)
        self.VER_ANALISIS.setObjectName(u"VER_ANALISIS")
        self.VER_ANALISIS.setGeometry(QRect(40, 250, 141, 21))
        self.comboBox_trazaA_4 = QComboBox(self.groupBox_60)
        self.comboBox_trazaA_4.setObjectName(u"comboBox_trazaA_4")
        self.comboBox_trazaA_4.setGeometry(QRect(170, 90, 91, 21))
        self.comboBox_trazaA_4.setMaxVisibleItems(6)
        self.radioButton_tipoanalisis = QRadioButton(self.groupBox_60)
        self.radioButton_tipoanalisis.setObjectName(u"radioButton_tipoanalisis")
        self.radioButton_tipoanalisis.setGeometry(QRect(10, 140, 95, 20))
        self.radioButton_tipoanalisis_2 = QRadioButton(self.groupBox_60)
        self.radioButton_tipoanalisis_2.setObjectName(u"radioButton_tipoanalisis_2")
        self.radioButton_tipoanalisis_2.setGeometry(QRect(10, 160, 95, 20))
        self.radioButton_tipoanalisis_3 = QRadioButton(self.groupBox_60)
        self.radioButton_tipoanalisis_3.setObjectName(u"radioButton_tipoanalisis_3")
        self.radioButton_tipoanalisis_3.setGeometry(QRect(10, 180, 95, 20))
        self.SMOOTH_ON_2 = QRadioButton(self.groupBox_60)
        self.SMOOTH_ON_2.setObjectName(u"SMOOTH_ON_2")
        self.SMOOTH_ON_2.setGeometry(QRect(140, 140, 111, 20))
        self.SMOOTH_OFF_2 = QRadioButton(self.groupBox_60)
        self.SMOOTH_OFF_2.setObjectName(u"SMOOTH_OFF_2")
        self.SMOOTH_OFF_2.setGeometry(QRect(140, 180, 111, 20))
        self.label_61 = QLabel(self.groupBox_60)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(140, 160, 121, 16))
        self.label_61.setFont(font3)
        self.k_factor_2 = QLineEdit(self.groupBox_60)
        self.k_factor_2.setObjectName(u"k_factor_2")
        self.k_factor_2.setGeometry(QRect(230, 160, 41, 16))
        self.k_factor_2.setReadOnly(False)
        self.GUARDAR_EXCEL = QPushButton(self.groupBox_60)
        self.GUARDAR_EXCEL.setObjectName(u"GUARDAR_EXCEL")
        self.GUARDAR_EXCEL.setGeometry(QRect(30, 340, 141, 21))
        self.save_path_19 = QLineEdit(self.groupBox_60)
        self.save_path_19.setObjectName(u"save_path_19")
        self.save_path_19.setGeometry(QRect(10, 310, 211, 20))
        self.save_path_19.setReadOnly(False)
        self.toolButton_load_18 = QToolButton(self.groupBox_60)
        self.toolButton_load_18.setObjectName(u"toolButton_load_18")
        self.toolButton_load_18.setGeometry(QRect(230, 310, 31, 21))
        self.progressBar_2 = QProgressBar(self.groupBox_60)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(70, 370, 118, 23))
        self.progressBar_2.setValue(24)
        self.load_path_19 = QLineEdit(self.groupBox_60)
        self.load_path_19.setObjectName(u"load_path_19")
        self.load_path_19.setGeometry(QRect(60, 90, 91, 20))
        self.load_path_19.setReadOnly(False)
        self.label_170 = QLabel(self.groupBox_60)
        self.label_170.setObjectName(u"label_170")
        self.label_170.setGeometry(QRect(10, 90, 67, 21))
        self.RANGO_MEDIDA = QRadioButton(self.groupBox_60)
        self.RANGO_MEDIDA.setObjectName(u"RANGO_MEDIDA")
        self.RANGO_MEDIDA.setGeometry(QRect(140, 110, 111, 20))
        self.RANGO_OBJETO = QRadioButton(self.groupBox_60)
        self.RANGO_OBJETO.setObjectName(u"RANGO_OBJETO")
        self.RANGO_OBJETO.setGeometry(QRect(10, 110, 111, 20))
        self.radioButton_tipoanalisis_4 = QRadioButton(self.groupBox_60)
        self.radioButton_tipoanalisis_4.setObjectName(u"radioButton_tipoanalisis_4")
        self.radioButton_tipoanalisis_4.setGeometry(QRect(10, 210, 95, 20))
        self.textBrowser_4 = QTextBrowser(self.analisis)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(850, 520, 421, 121))
        self.groupBox_61 = QGroupBox(self.analisis)
        self.groupBox_61.setObjectName(u"groupBox_61")
        self.groupBox_61.setGeometry(QRect(190, 510, 421, 131))
        self.load_path_18 = QLineEdit(self.groupBox_61)
        self.load_path_18.setObjectName(u"load_path_18")
        self.load_path_18.setGeometry(QRect(140, 40, 211, 20))
        self.load_path_18.setReadOnly(False)
        self.CONEXION_1 = QPushButton(self.groupBox_61)
        self.CONEXION_1.setObjectName(u"CONEXION_1")
        self.CONEXION_1.setGeometry(QRect(150, 90, 141, 21))
        self.MODELO_1 = QRadioButton(self.groupBox_61)
        self.MODELO_1.setObjectName(u"MODELO_1")
        self.MODELO_1.setGeometry(QRect(40, 90, 95, 20))
        self.MODELO_2 = QRadioButton(self.groupBox_61)
        self.MODELO_2.setObjectName(u"MODELO_2")
        self.MODELO_2.setGeometry(QRect(40, 110, 95, 20))
        self.label_169 = QLabel(self.groupBox_61)
        self.label_169.setObjectName(u"label_169")
        self.label_169.setGeometry(QRect(30, 40, 67, 21))
        self.label_161 = QLabel(self.analisis)
        self.label_161.setObjectName(u"label_161")
        self.label_161.setGeometry(QRect(370, 0, 191, 31))
        self.label_161.setFont(font1)
        self.tabWidget.addTab(self.analisis, "")
        self.fit = QWidget()
        self.fit.setObjectName(u"fit")
        self.frame_5 = QFrame(self.fit)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 10, 1261, 511))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.verticalLayoutWidget_3 = QWidget(self.frame_5)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 20, 921, 481))
        self.mpl_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.mpl_3.setObjectName(u"mpl_3")
        self.mpl_3.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.frame_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(310, 0, 191, 31))
        self.label_5.setFont(font1)
        self.AJUSTA = QPushButton(self.frame_5)
        self.AJUSTA.setObjectName(u"AJUSTA")
        self.AJUSTA.setGeometry(QRect(970, 320, 161, 21))
        self.groupBox_16 = QGroupBox(self.frame_5)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(960, 350, 271, 151))
        self.comboBox_mag_fit = QComboBox(self.groupBox_16)
        self.comboBox_mag_fit.setObjectName(u"comboBox_mag_fit")
        self.comboBox_mag_fit.setGeometry(QRect(10, 57, 71, 21))
        self.comboBox_mag_fit.setMaxVisibleItems(6)
        self.n_func = QLineEdit(self.groupBox_16)
        self.n_func.setObjectName(u"n_func")
        self.n_func.setGeometry(QRect(180, 57, 71, 20))
        self.n_func.setReadOnly(False)
        self.label_35 = QLabel(self.groupBox_16)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(90, 30, 111, 21))
        self.label_35.setFont(font3)
        self.label_31 = QLabel(self.groupBox_16)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(170, 29, 101, 20))
        self.label_31.setFont(font3)
        self.label_22 = QLabel(self.groupBox_16)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 30, 111, 20))
        self.label_22.setFont(font3)
        self.comboBox_fit_alg = QComboBox(self.groupBox_16)
        self.comboBox_fit_alg.setObjectName(u"comboBox_fit_alg")
        self.comboBox_fit_alg.setGeometry(QRect(90, 57, 71, 21))
        self.label_27 = QLabel(self.groupBox_16)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 90, 191, 21))
        self.label_27.setFont(font3)
        self.f_high = QLineEdit(self.groupBox_16)
        self.f_high.setObjectName(u"f_high")
        self.f_high.setGeometry(QRect(150, 120, 111, 20))
        self.f_high.setReadOnly(False)
        self.f_low = QLineEdit(self.groupBox_16)
        self.f_low.setObjectName(u"f_low")
        self.f_low.setGeometry(QRect(10, 120, 111, 20))
        self.f_low.setReadOnly(False)
        self.label_7 = QLabel(self.frame_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(970, 440, 251, 51))
        self.label_7.setPixmap(QPixmap(u"../.designer/backup/ecuacion_gompertz.gif"))
        self.label_7.setScaledContents(True)
        self.groupBox_10 = QGroupBox(self.frame_5)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(960, 220, 271, 91))
        self.load_path_3 = QLineEdit(self.groupBox_10)
        self.load_path_3.setObjectName(u"load_path_3")
        self.load_path_3.setGeometry(QRect(10, 30, 211, 20))
        self.load_path_3.setReadOnly(False)
        self.LOAD_fit_data = QPushButton(self.groupBox_10)
        self.LOAD_fit_data.setObjectName(u"LOAD_fit_data")
        self.LOAD_fit_data.setGeometry(QRect(10, 60, 161, 21))
        self.toolButton_load_3 = QToolButton(self.groupBox_10)
        self.toolButton_load_3.setObjectName(u"toolButton_load_3")
        self.toolButton_load_3.setGeometry(QRect(230, 30, 31, 21))
        self.groupBox_17 = QGroupBox(self.frame_5)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(960, 10, 271, 201))
        self.load_path_4 = QLineEdit(self.groupBox_17)
        self.load_path_4.setObjectName(u"load_path_4")
        self.load_path_4.setGeometry(QRect(10, 30, 211, 20))
        self.load_path_4.setReadOnly(False)
        self.toolButton_load_4 = QToolButton(self.groupBox_17)
        self.toolButton_load_4.setObjectName(u"toolButton_load_4")
        self.toolButton_load_4.setGeometry(QRect(230, 30, 31, 21))
        self.spinBox_pollo = QSpinBox(self.groupBox_17)
        self.spinBox_pollo.setObjectName(u"spinBox_pollo")
        self.spinBox_pollo.setGeometry(QRect(80, 60, 44, 26))
        self.label_8 = QLabel(self.groupBox_17)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 60, 67, 17))
        self.label_9 = QLabel(self.groupBox_17)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(150, 60, 67, 17))
        self.spinBox_medida = QSpinBox(self.groupBox_17)
        self.spinBox_medida.setObjectName(u"spinBox_medida")
        self.spinBox_medida.setGeometry(QRect(220, 60, 44, 26))
        self.LOAD_fit_data_2 = QPushButton(self.groupBox_17)
        self.LOAD_fit_data_2.setObjectName(u"LOAD_fit_data_2")
        self.LOAD_fit_data_2.setGeometry(QRect(10, 100, 141, 21))
        font12 = QFont()
        font12.setFamilies([u"MS Shell Dlg 2"])
        font12.setPointSize(9)
        self.LOAD_fit_data_2.setFont(font12)
        self.SAVE_fit = QPushButton(self.groupBox_17)
        self.SAVE_fit.setObjectName(u"SAVE_fit")
        self.SAVE_fit.setGeometry(QRect(156, 100, 111, 21))
        self.SAVE_fit.setFont(font12)
        self.SAVE_fit_2 = QPushButton(self.groupBox_17)
        self.SAVE_fit_2.setObjectName(u"SAVE_fit_2")
        self.SAVE_fit_2.setGeometry(QRect(90, 180, 111, 21))
        self.SAVE_fit_2.setFont(font12)
        self.spinBox_pollo_db_3 = QSpinBox(self.groupBox_17)
        self.spinBox_pollo_db_3.setObjectName(u"spinBox_pollo_db_3")
        self.spinBox_pollo_db_3.setGeometry(QRect(210, 130, 51, 41))
        font13 = QFont()
        font13.setFamilies([u"Sans"])
        font13.setPointSize(18)
        font13.setBold(False)
        self.spinBox_pollo_db_3.setFont(font13)
        self.spinBox_pollo_db_3.setMinimum(0)
        self.spinBox_pollo_db_3.setMaximum(99)
        self.label_64 = QLabel(self.groupBox_17)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(150, 130, 61, 31))
        font14 = QFont()
        font14.setFamilies([u"Sans"])
        font14.setPointSize(11)
        font14.setBold(False)
        self.label_64.setFont(font14)
        self.label_63 = QLabel(self.groupBox_17)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(20, 150, 61, 31))
        self.label_63.setFont(font14)
        self.label_65 = QLabel(self.groupBox_17)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(150, 150, 61, 31))
        self.label_65.setFont(font14)
        self.last_medida_2 = QLCDNumber(self.frame_5)
        self.last_medida_2.setObjectName(u"last_medida_2")
        self.last_medida_2.setGeometry(QRect(1050, 140, 41, 41))
        self.last_medida_2.setFont(font5)
        self.last_medida_2.setLineWidth(1)
        self.last_medida_2.setDigitCount(2)
        self.groupBox_11 = QGroupBox(self.fit)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(30, 670, 241, 121))
        self.label_24 = QLabel(self.groupBox_11)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 31, 20))
        self.label_24.setFont(font3)
        self.param_B1 = QLineEdit(self.groupBox_11)
        self.param_B1.setObjectName(u"param_B1")
        self.param_B1.setGeometry(QRect(100, 30, 61, 20))
        self.param_B1.setReadOnly(False)
        self.label_25 = QLabel(self.groupBox_11)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 60, 31, 20))
        self.label_25.setFont(font3)
        self.param_C1 = QLineEdit(self.groupBox_11)
        self.param_C1.setObjectName(u"param_C1")
        self.param_C1.setGeometry(QRect(100, 60, 61, 20))
        self.param_C1.setReadOnly(False)
        self.param_D1 = QLineEdit(self.groupBox_11)
        self.param_D1.setObjectName(u"param_D1")
        self.param_D1.setGeometry(QRect(100, 90, 61, 20))
        self.param_D1.setReadOnly(False)
        self.label_26 = QLabel(self.groupBox_11)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 90, 31, 20))
        self.label_26.setFont(font3)
        self.param_C1_L = QLineEdit(self.groupBox_11)
        self.param_C1_L.setObjectName(u"param_C1_L")
        self.param_C1_L.setGeometry(QRect(30, 60, 61, 20))
        self.param_C1_L.setReadOnly(False)
        self.param_D1_L = QLineEdit(self.groupBox_11)
        self.param_D1_L.setObjectName(u"param_D1_L")
        self.param_D1_L.setGeometry(QRect(30, 90, 61, 20))
        self.param_D1_L.setReadOnly(False)
        self.param_B1_L = QLineEdit(self.groupBox_11)
        self.param_B1_L.setObjectName(u"param_B1_L")
        self.param_B1_L.setGeometry(QRect(30, 30, 61, 20))
        self.param_B1_L.setReadOnly(False)
        self.param_B1_H = QLineEdit(self.groupBox_11)
        self.param_B1_H.setObjectName(u"param_B1_H")
        self.param_B1_H.setGeometry(QRect(170, 30, 61, 20))
        self.param_B1_H.setReadOnly(False)
        self.param_D1_H = QLineEdit(self.groupBox_11)
        self.param_D1_H.setObjectName(u"param_D1_H")
        self.param_D1_H.setGeometry(QRect(170, 90, 61, 20))
        self.param_D1_H.setReadOnly(False)
        self.param_C1_H = QLineEdit(self.groupBox_11)
        self.param_C1_H.setObjectName(u"param_C1_H")
        self.param_C1_H.setGeometry(QRect(170, 60, 61, 20))
        self.param_C1_H.setReadOnly(False)
        self.groupBox_15 = QGroupBox(self.fit)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(310, 670, 241, 121))
        self.label_32 = QLabel(self.groupBox_15)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 21, 20))
        self.label_32.setFont(font3)
        self.param_B3 = QLineEdit(self.groupBox_15)
        self.param_B3.setObjectName(u"param_B3")
        self.param_B3.setGeometry(QRect(100, 30, 61, 20))
        self.param_B3.setReadOnly(False)
        self.label_33 = QLabel(self.groupBox_15)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 60, 31, 20))
        self.label_33.setFont(font3)
        self.param_C3 = QLineEdit(self.groupBox_15)
        self.param_C3.setObjectName(u"param_C3")
        self.param_C3.setGeometry(QRect(100, 60, 61, 20))
        self.param_C3.setReadOnly(False)
        self.param_D3 = QLineEdit(self.groupBox_15)
        self.param_D3.setObjectName(u"param_D3")
        self.param_D3.setGeometry(QRect(100, 90, 61, 20))
        self.param_D3.setReadOnly(False)
        self.label_34 = QLabel(self.groupBox_15)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 90, 31, 20))
        self.label_34.setFont(font3)
        self.param_B3_L = QLineEdit(self.groupBox_15)
        self.param_B3_L.setObjectName(u"param_B3_L")
        self.param_B3_L.setGeometry(QRect(30, 30, 61, 20))
        self.param_B3_L.setReadOnly(False)
        self.param_B3_H = QLineEdit(self.groupBox_15)
        self.param_B3_H.setObjectName(u"param_B3_H")
        self.param_B3_H.setGeometry(QRect(170, 30, 61, 20))
        self.param_B3_H.setReadOnly(False)
        self.param_C3_H = QLineEdit(self.groupBox_15)
        self.param_C3_H.setObjectName(u"param_C3_H")
        self.param_C3_H.setGeometry(QRect(170, 60, 61, 20))
        self.param_C3_H.setReadOnly(False)
        self.param_C3_L = QLineEdit(self.groupBox_15)
        self.param_C3_L.setObjectName(u"param_C3_L")
        self.param_C3_L.setGeometry(QRect(30, 60, 61, 20))
        self.param_C3_L.setReadOnly(False)
        self.param_D3_H = QLineEdit(self.groupBox_15)
        self.param_D3_H.setObjectName(u"param_D3_H")
        self.param_D3_H.setGeometry(QRect(170, 90, 61, 20))
        self.param_D3_H.setReadOnly(False)
        self.param_D3_L = QLineEdit(self.groupBox_15)
        self.param_D3_L.setObjectName(u"param_D3_L")
        self.param_D3_L.setGeometry(QRect(30, 90, 61, 20))
        self.param_D3_L.setReadOnly(False)
        self.textBrowser_3 = QTextBrowser(self.fit)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(580, 530, 681, 271))
        self.label_6 = QLabel(self.fit)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 540, 231, 41))
        self.groupBox_12 = QGroupBox(self.fit)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(310, 530, 241, 121))
        self.label_28 = QLabel(self.groupBox_12)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 30, 21, 20))
        self.label_28.setFont(font3)
        self.param_B2 = QLineEdit(self.groupBox_12)
        self.param_B2.setObjectName(u"param_B2")
        self.param_B2.setGeometry(QRect(100, 30, 61, 20))
        self.param_B2.setReadOnly(False)
        self.label_29 = QLabel(self.groupBox_12)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 60, 21, 20))
        self.label_29.setFont(font3)
        self.param_C2 = QLineEdit(self.groupBox_12)
        self.param_C2.setObjectName(u"param_C2")
        self.param_C2.setGeometry(QRect(100, 60, 61, 20))
        self.param_C2.setReadOnly(False)
        self.param_D2 = QLineEdit(self.groupBox_12)
        self.param_D2.setObjectName(u"param_D2")
        self.param_D2.setGeometry(QRect(100, 90, 61, 20))
        self.param_D2.setReadOnly(False)
        self.label_30 = QLabel(self.groupBox_12)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 90, 21, 20))
        self.label_30.setFont(font3)
        self.param_C2_L = QLineEdit(self.groupBox_12)
        self.param_C2_L.setObjectName(u"param_C2_L")
        self.param_C2_L.setGeometry(QRect(30, 60, 61, 20))
        self.param_C2_L.setReadOnly(False)
        self.param_B2_L = QLineEdit(self.groupBox_12)
        self.param_B2_L.setObjectName(u"param_B2_L")
        self.param_B2_L.setGeometry(QRect(30, 30, 61, 20))
        self.param_B2_L.setReadOnly(False)
        self.param_D2_L = QLineEdit(self.groupBox_12)
        self.param_D2_L.setObjectName(u"param_D2_L")
        self.param_D2_L.setGeometry(QRect(30, 90, 61, 20))
        self.param_D2_L.setReadOnly(False)
        self.param_B2_H = QLineEdit(self.groupBox_12)
        self.param_B2_H.setObjectName(u"param_B2_H")
        self.param_B2_H.setGeometry(QRect(170, 30, 61, 20))
        self.param_B2_H.setReadOnly(False)
        self.param_D2_H = QLineEdit(self.groupBox_12)
        self.param_D2_H.setObjectName(u"param_D2_H")
        self.param_D2_H.setGeometry(QRect(170, 90, 61, 20))
        self.param_D2_H.setReadOnly(False)
        self.param_C2_H = QLineEdit(self.groupBox_12)
        self.param_C2_H.setObjectName(u"param_C2_H")
        self.param_C2_H.setGeometry(QRect(170, 60, 61, 20))
        self.param_C2_H.setReadOnly(False)
        self.label_23 = QLabel(self.fit)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(40, 610, 31, 20))
        self.label_23.setFont(font3)
        self.param_A1 = QLineEdit(self.fit)
        self.param_A1.setObjectName(u"param_A1")
        self.param_A1.setGeometry(QRect(130, 610, 61, 20))
        self.param_A1.setReadOnly(False)
        self.param_A1_H = QLineEdit(self.fit)
        self.param_A1_H.setObjectName(u"param_A1_H")
        self.param_A1_H.setGeometry(QRect(200, 610, 61, 20))
        self.param_A1_H.setReadOnly(False)
        self.param_A1_L = QLineEdit(self.fit)
        self.param_A1_L.setObjectName(u"param_A1_L")
        self.param_A1_L.setGeometry(QRect(60, 610, 61, 20))
        self.param_A1_L.setReadOnly(False)
        self.label_62 = QLabel(self.fit)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(980, 150, 61, 31))
        self.label_62.setFont(font14)
        self.tabWidget.addTab(self.fit, "")

        self.horizontalLayout_2.addWidget(self.tabWidget)


        self.horizontalLayout_13.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Interfaz Redpitaya", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"AN\u00c1LISIS DE DATOS", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"DATOS MEDIDOS", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"CONTROL REMOTO REDPITAYA", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n de Medida", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"N\u00famero Puntos", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Freq. Inicial", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Freq. Final", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"R shunt", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"[1-801]", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"[0-5]", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"[0-1V]", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"V. Oscilador", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Barrido", None))
        self.radioButton_lineal.setText(QCoreApplication.translate("MainWindow", u"Lineal", None))
        self.radioButton_log.setText(QCoreApplication.translate("MainWindow", u"Logar\u00edtmico", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n BIAS", None))
        self.radioButton_DC_ON.setText(QCoreApplication.translate("MainWindow", u"DC bias ON", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Nivel DC [-40V,40V]", None))
        self.radioButton_DC_OFF.setText(QCoreApplication.translate("MainWindow", u"DC bias OFF", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Procedimiento Correlaci\u00f3n", None))
        self.radioButton_Corre.setText(QCoreApplication.translate("MainWindow", u"Software", None))
        self.radioButton_F_Corre.setText(QCoreApplication.translate("MainWindow", u"Hardware", None))
        self.n_ciclos.setText("")
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"n\u00ba de ciclos[0-10]", None))
        self.MEDIR.setText(QCoreApplication.translate("MainWindow", u"MEDIR", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"PLOT", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"EJE Y - (ROJO)", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"EJE Y - (AZUL)", None))
        self.REDRAW_MEASURE.setText(QCoreApplication.translate("MainWindow", u"REDIBUJAR\n"
"MEDIDA", None))
        self.SMOOTH_ON.setText(QCoreApplication.translate("MainWindow", u"Smooth on", None))
        self.SMOOTH_OFF.setText(QCoreApplication.translate("MainWindow", u"Smooth off", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"factor k   [1-9]", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("MainWindow", u"FICHERO CSV", None))
        self.LOAD_M.setText(QCoreApplication.translate("MainWindow", u"CARGAR/REDIBUJAR DATOS - CSV", None))
        self.toolButton_load.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.SAVE_M.setText(QCoreApplication.translate("MainWindow", u"GUARDAR MEDIDA - CSV", None))
        self.toolButton_save.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.SAVE_cfg.setText(QCoreApplication.translate("MainWindow", u"SALVAR CONFIG.", None))
        self.SAVE_DB.setText(QCoreApplication.translate("MainWindow", u"SALVAR \n"
" BASE DE DATOS", None))
        self.toolButton_load_db.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"BASE DE DATOS", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"\u00daLTIMO SUJETO", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u00daLTIMA MEDIDA", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"SUJETO", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"MEDIDA", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"ESTADO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.datos), QCoreApplication.translate("MainWindow", u"SENSOR PECTORAL", None))
        self.GO_CAL.setText(QCoreApplication.translate("MainWindow", u"COMENZAR \n"
" CALIBRACI\u00d3N", None))
        self.SAVE_CAL.setText(QCoreApplication.translate("MainWindow", u"Guardar Calibraci\u00f3n", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n Calibraci\u00f3n", None))
        self.radioButton_config_cal_2.setText(QCoreApplication.translate("MainWindow", u"Abierto, Corto", None))
        self.radioButton_config_cal_1.setText(QCoreApplication.translate("MainWindow", u"Carga, Abierto, Corto", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"C Load (fF)", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"G Load (S)", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Puntos de Calibraci\u00f3n", None))
        self.radioButton_pto_cal_usuario.setText(QCoreApplication.translate("MainWindow", u"Usuario", None))
        self.radioButton_pto_cal_medidor.setText(QCoreApplication.translate("MainWindow", u"Medidor", None))
        self.LOAD_CAL.setText(QCoreApplication.translate("MainWindow", u"Cargar Calibraci\u00f3n", None))
        self.toolButton_load_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_save_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n de la Calibraci\u00f3n", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"N\u00famero Puntos", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Freq. Inicial", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Freq. Final", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"R shunt", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"[1-801]", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"[0-5]", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"[0-1V]", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"V. Oscilador", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Tipo Barrido", None))
        self.radioButton_lineal_2.setText(QCoreApplication.translate("MainWindow", u"Lineal", None))
        self.radioButton_log_2.setText(QCoreApplication.translate("MainWindow", u"Logar\u00edtmico", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Configuraci\u00f3n BIAS", None))
        self.radioButton_DC_OFF_2.setText(QCoreApplication.translate("MainWindow", u"DC bias OFF", None))
        self.radioButton_DC_ON_2.setText(QCoreApplication.translate("MainWindow", u"DC bias ON", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Nivel DC [-40V,40V]", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Procedimiento Correlaci\u00f3n", None))
        self.radioButton_Corre_2.setText(QCoreApplication.translate("MainWindow", u"Software", None))
        self.radioButton_F_Corre_2.setText(QCoreApplication.translate("MainWindow", u"Hardware", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"n\u00ba de ciclos[0-10]", None))
        self.n_ciclos_2.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibracion), QCoreApplication.translate("MainWindow", u"CALIBRACI\u00d3N", None))
        self.groupBox_60.setTitle(QCoreApplication.translate("MainWindow", u"Datos desde Base de Datos HDF5", None))
        self.toolButton_load_17.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_167.setText(QCoreApplication.translate("MainWindow", u"Objeto", None))
        self.label_168.setText(QCoreApplication.translate("MainWindow", u"Medida", None))
        self.VER_ANALISIS.setText(QCoreApplication.translate("MainWindow", u"VER ANALISISS", None))
        self.radioButton_tipoanalisis.setText(QCoreApplication.translate("MainWindow", u"reflujo", None))
        self.radioButton_tipoanalisis_2.setText(QCoreApplication.translate("MainWindow", u"agua", None))
        self.radioButton_tipoanalisis_3.setText(QCoreApplication.translate("MainWindow", u"Yake", None))
        self.SMOOTH_ON_2.setText(QCoreApplication.translate("MainWindow", u"Smooth on", None))
        self.SMOOTH_OFF_2.setText(QCoreApplication.translate("MainWindow", u"Smooth off", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"factor k   [1-9]", None))
        self.GUARDAR_EXCEL.setText(QCoreApplication.translate("MainWindow", u"GUARDAR EXCEL", None))
        self.toolButton_load_18.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_170.setText(QCoreApplication.translate("MainWindow", u"rango", None))
        self.RANGO_MEDIDA.setText(QCoreApplication.translate("MainWindow", u"Medida", None))
        self.RANGO_OBJETO.setText(QCoreApplication.translate("MainWindow", u"Objeto", None))
        self.radioButton_tipoanalisis_4.setText(QCoreApplication.translate("MainWindow", u"reflujo_2", None))
        self.groupBox_61.setTitle(QCoreApplication.translate("MainWindow", u"Conexion a redpitaya", None))
        self.CONEXION_1.setText(QCoreApplication.translate("MainWindow", u"CONEXI\u00d3N", None))
        self.MODELO_1.setText(QCoreApplication.translate("MainWindow", u"7010", None))
        self.MODELO_2.setText(QCoreApplication.translate("MainWindow", u"7020", None))
        self.label_169.setText(QCoreApplication.translate("MainWindow", u"IP redpitaya", None))
        self.label_161.setText(QCoreApplication.translate("MainWindow", u"VISOR DE MEDIDAS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analisis), QCoreApplication.translate("MainWindow", u"ANALISIS", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"AJUSTE DE GOMPERTZ", None))
        self.AJUSTA.setText(QCoreApplication.translate("MainWindow", u"AJUSTA MEDIDA", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("MainWindow", u"Ajuste", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"M\u00e9todo ", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Num funciones", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Magnitud ", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Rango frecuencias", None))
        self.label_7.setText("")
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Datos desde Fichero CSV", None))
        self.LOAD_fit_data.setText(QCoreApplication.translate("MainWindow", u"AJUSTA DATOS CSV", None))
        self.toolButton_load_3.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"Datos desde Base de Datos HDF5", None))
        self.toolButton_load_4.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Objeto", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Medida", None))
        self.LOAD_fit_data_2.setText(QCoreApplication.translate("MainWindow", u"AJUSTA BASE DATOS", None))
        self.SAVE_fit.setText(QCoreApplication.translate("MainWindow", u"SALVA AJUSTE", None))
        self.SAVE_fit_2.setText(QCoreApplication.translate("MainWindow", u"SALVA ESTADO", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"ESTADO veamos", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"obtenido", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"deseado", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"GOMPERTZ 1", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"GOMPERTZ 3", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"VALORES INICIALES y LIMITES", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"GOMPERTZ 2", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"ESTADO veamos", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fit), QCoreApplication.translate("MainWindow", u"AJUSTE", None))
    # retranslateUi

