# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MIOPATIA_rafa.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1326, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1326, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1326, 900))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pollo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(120, 120))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setMinimumSize(QtCore.QSize(440, 510))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setObjectName("tabWidget")
        self.datos = QtWidgets.QWidget()
        self.datos.setObjectName("datos")
        self.frame_3 = QtWidgets.QFrame(self.datos)
        self.frame_3.setGeometry(QtCore.QRect(-1, 430, 631, 381))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 611, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mpl_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mpl_2.setContentsMargins(0, 0, 0, 0)
        self.mpl_2.setObjectName("mpl_2")
        self.label_4 = QtWidgets.QLabel(self.datos)
        self.label_4.setGeometry(QtCore.QRect(240, 424, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.datos)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.datos)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 631, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 611, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mpl_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mpl_1.setContentsMargins(0, 0, 0, 0)
        self.mpl_1.setObjectName("mpl_1")
        self.label = QtWidgets.QLabel(self.datos)
        self.label.setGeometry(QtCore.QRect(650, 10, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.datos)
        self.frame_4.setGeometry(QtCore.QRect(650, 50, 441, 770))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(441, 770))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox_13 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 6, 421, 301))
        self.groupBox_13.setAutoFillBackground(False)
        self.groupBox_13.setObjectName("groupBox_13")
        self.f_inicial = QtWidgets.QLineEdit(self.groupBox_13)
        self.f_inicial.setGeometry(QtCore.QRect(130, 30, 71, 20))
        self.f_inicial.setReadOnly(False)
        self.f_inicial.setObjectName("f_inicial")
        self.n_puntos = QtWidgets.QLineEdit(self.groupBox_13)
        self.n_puntos.setGeometry(QtCore.QRect(130, 70, 71, 20))
        self.n_puntos.setReadOnly(False)
        self.n_puntos.setObjectName("n_puntos")
        self.label_42 = QtWidgets.QLabel(self.groupBox_13)
        self.label_42.setGeometry(QtCore.QRect(20, 60, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_44 = QtWidgets.QLabel(self.groupBox_13)
        self.label_44.setGeometry(QtCore.QRect(20, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_46 = QtWidgets.QLabel(self.groupBox_13)
        self.label_46.setGeometry(QtCore.QRect(30, 160, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.f_final = QtWidgets.QLineEdit(self.groupBox_13)
        self.f_final.setGeometry(QtCore.QRect(130, 160, 71, 20))
        self.f_final.setReadOnly(False)
        self.f_final.setObjectName("f_final")
        self.label_43 = QtWidgets.QLabel(self.groupBox_13)
        self.label_43.setGeometry(QtCore.QRect(240, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.ancho_banda = QtWidgets.QLineEdit(self.groupBox_13)
        self.ancho_banda.setGeometry(QtCore.QRect(330, 30, 71, 20))
        self.ancho_banda.setReadOnly(False)
        self.ancho_banda.setObjectName("ancho_banda")
        self.label_50 = QtWidgets.QLabel(self.groupBox_13)
        self.label_50.setGeometry(QtCore.QRect(40, 80, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_13)
        self.label_51.setGeometry(QtCore.QRect(260, 40, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_13)
        self.label_52.setGeometry(QtCore.QRect(40, 130, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_13)
        self.label_53.setGeometry(QtCore.QRect(20, 110, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.vosc = QtWidgets.QLineEdit(self.groupBox_13)
        self.vosc.setGeometry(QtCore.QRect(130, 120, 71, 20))
        self.vosc.setReadOnly(False)
        self.vosc.setObjectName("vosc")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox.setGeometry(QtCore.QRect(240, 70, 161, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_lineal = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_lineal.setGeometry(QtCore.QRect(20, 27, 111, 23))
        self.radioButton_lineal.setObjectName("radioButton_lineal")
        self.radioButton_log = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_log.setGeometry(QtCore.QRect(20, 50, 111, 23))
        self.radioButton_log.setObjectName("radioButton_log")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 160, 171, 131))
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_DC_OFF = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_DC_OFF.setGeometry(QtCore.QRect(20, 50, 111, 23))
        self.radioButton_DC_OFF.setObjectName("radioButton_DC_OFF")
        self.radioButton_DC_ON = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_DC_ON.setGeometry(QtCore.QRect(20, 27, 111, 23))
        self.radioButton_DC_ON.setObjectName("radioButton_DC_ON")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 76, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.nivel_DC = QtWidgets.QLineEdit(self.groupBox_3)
        self.nivel_DC.setGeometry(QtCore.QRect(40, 100, 71, 20))
        self.nivel_DC.setReadOnly(False)
        self.nivel_DC.setObjectName("nivel_DC")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 200, 181, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 50, 91, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.MEDIR = QtWidgets.QPushButton(self.frame_4)
        self.MEDIR.setGeometry(QtCore.QRect(160, 470, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MEDIR.setFont(font)
        self.MEDIR.setObjectName("MEDIR")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 131, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_trazaA = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_trazaA.setGeometry(QtCore.QRect(20, 47, 91, 21))
        self.comboBox_trazaA.setMaxVisibleItems(6)
        self.comboBox_trazaA.setObjectName("comboBox_trazaA")
        self.comboBox_trazaB = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_trazaB.setGeometry(QtCore.QRect(20, 98, 91, 21))
        self.comboBox_trazaB.setMaxVisibleItems(6)
        self.comboBox_trazaB.setObjectName("comboBox_trazaB")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(20, 24, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 74, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.REDRAW_MEASURE = QtWidgets.QPushButton(self.groupBox_2)
        self.REDRAW_MEASURE.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.REDRAW_MEASURE.setObjectName("REDRAW_MEASURE")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setGeometry(QtCore.QRect(10, 520, 421, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_18.setGeometry(QtCore.QRect(160, 310, 271, 151))
        self.groupBox_18.setObjectName("groupBox_18")
        self.LOAD_M = QtWidgets.QPushButton(self.groupBox_18)
        self.LOAD_M.setGeometry(QtCore.QRect(10, 30, 241, 21))
        self.LOAD_M.setObjectName("LOAD_M")
        self.toolButton_load = QtWidgets.QToolButton(self.groupBox_18)
        self.toolButton_load.setGeometry(QtCore.QRect(220, 60, 31, 21))
        self.toolButton_load.setObjectName("toolButton_load")
        self.load_path = QtWidgets.QLineEdit(self.groupBox_18)
        self.load_path.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.load_path.setReadOnly(False)
        self.load_path.setObjectName("load_path")
        self.SAVE_M = QtWidgets.QPushButton(self.groupBox_18)
        self.SAVE_M.setGeometry(QtCore.QRect(10, 90, 241, 21))
        self.SAVE_M.setObjectName("SAVE_M")
        self.toolButton_save = QtWidgets.QToolButton(self.groupBox_18)
        self.toolButton_save.setGeometry(QtCore.QRect(220, 120, 31, 21))
        self.toolButton_save.setObjectName("toolButton_save")
        self.save_path = QtWidgets.QLineEdit(self.groupBox_18)
        self.save_path.setGeometry(QtCore.QRect(10, 120, 201, 20))
        self.save_path.setReadOnly(False)
        self.save_path.setObjectName("save_path")
        self.SAVE_cfg = QtWidgets.QPushButton(self.datos)
        self.SAVE_cfg.setGeometry(QtCore.QRect(1110, 50, 161, 41))
        self.SAVE_cfg.setObjectName("SAVE_cfg")
        self.last_medida = QtWidgets.QLCDNumber(self.datos)
        self.last_medida.setGeometry(QtCore.QRect(1140, 280, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.last_medida.setFont(font)
        self.last_medida.setLineWidth(1)
        self.last_medida.setDigitCount(2)
        self.last_medida.setObjectName("last_medida")
        self.last_pollo = QtWidgets.QLCDNumber(self.datos)
        self.last_pollo.setGeometry(QtCore.QRect(1140, 160, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.last_pollo.setFont(font)
        self.last_pollo.setLineWidth(1)
        self.last_pollo.setDigitCount(2)
        self.last_pollo.setObjectName("last_pollo")
        self.SAVE_DB = QtWidgets.QPushButton(self.datos)
        self.SAVE_DB.setGeometry(QtCore.QRect(1100, 380, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SAVE_DB.setFont(font)
        self.SAVE_DB.setObjectName("SAVE_DB")
        self.load_path_db = QtWidgets.QLineEdit(self.datos)
        self.load_path_db.setGeometry(QtCore.QRect(1100, 670, 181, 20))
        self.load_path_db.setReadOnly(False)
        self.load_path_db.setObjectName("load_path_db")
        self.toolButton_load_db = QtWidgets.QToolButton(self.datos)
        self.toolButton_load_db.setGeometry(QtCore.QRect(1100, 700, 31, 21))
        self.toolButton_load_db.setObjectName("toolButton_load_db")
        self.spinBox_pollo_db = QtWidgets.QSpinBox(self.datos)
        self.spinBox_pollo_db.setGeometry(QtCore.QRect(1100, 479, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_pollo_db.setFont(font)
        self.spinBox_pollo_db.setObjectName("spinBox_pollo_db")
        self.spinBox_medida_db = QtWidgets.QSpinBox(self.datos)
        self.spinBox_medida_db.setGeometry(QtCore.QRect(1210, 479, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_medida_db.setFont(font)
        self.spinBox_medida_db.setMaximum(19)
        self.spinBox_medida_db.setObjectName("spinBox_medida_db")
        self.label_36 = QtWidgets.QLabel(self.datos)
        self.label_36.setGeometry(QtCore.QRect(1100, 640, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.datos)
        self.label_37.setGeometry(QtCore.QRect(1130, 130, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.datos)
        self.label_38.setGeometry(QtCore.QRect(1130, 250, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.datos)
        self.label_39.setGeometry(QtCore.QRect(1100, 459, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.datos)
        self.label_40.setGeometry(QtCore.QRect(1210, 459, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.spinBox_pollo_db_2 = QtWidgets.QSpinBox(self.datos)
        self.spinBox_pollo_db_2.setGeometry(QtCore.QRect(1156, 550, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_pollo_db_2.setFont(font)
        self.spinBox_pollo_db_2.setMaximum(3)
        self.spinBox_pollo_db_2.setObjectName("spinBox_pollo_db_2")
        self.label_41 = QtWidgets.QLabel(self.datos)
        self.label_41.setGeometry(QtCore.QRect(1120, 529, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.datos, "")
        self.calibracion = QtWidgets.QWidget()
        self.calibracion.setAcceptDrops(False)
        self.calibracion.setObjectName("calibracion")
        self.GO_CAL = QtWidgets.QPushButton(self.calibracion)
        self.GO_CAL.setGeometry(QtCore.QRect(60, 230, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GO_CAL.setFont(font)
        self.GO_CAL.setObjectName("GO_CAL")
        self.SAVE_CAL = QtWidgets.QPushButton(self.calibracion)
        self.SAVE_CAL.setGeometry(QtCore.QRect(340, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(10)
        self.SAVE_CAL.setFont(font)
        self.SAVE_CAL.setObjectName("SAVE_CAL")
        self.groupBox_5 = QtWidgets.QGroupBox(self.calibracion)
        self.groupBox_5.setGeometry(QtCore.QRect(60, 30, 241, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_config_cal_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_config_cal_2.setGeometry(QtCore.QRect(20, 140, 161, 23))
        self.radioButton_config_cal_2.setObjectName("radioButton_config_cal_2")
        self.radioButton_config_cal_1 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_config_cal_1.setGeometry(QtCore.QRect(20, 40, 201, 23))
        self.radioButton_config_cal_1.setObjectName("radioButton_config_cal_1")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(40, 70, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.c_load = QtWidgets.QLineEdit(self.groupBox_5)
        self.c_load.setGeometry(QtCore.QRect(130, 70, 71, 20))
        self.c_load.setReadOnly(False)
        self.c_load.setObjectName("c_load")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(40, 100, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.g_load = QtWidgets.QLineEdit(self.groupBox_5)
        self.g_load.setGeometry(QtCore.QRect(130, 100, 71, 20))
        self.g_load.setReadOnly(False)
        self.g_load.setObjectName("g_load")
        self.groupBox_6 = QtWidgets.QGroupBox(self.calibracion)
        self.groupBox_6.setGeometry(QtCore.QRect(340, 30, 221, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButton_pto_cal_usuario = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_pto_cal_usuario.setGeometry(QtCore.QRect(20, 70, 161, 23))
        self.radioButton_pto_cal_usuario.setObjectName("radioButton_pto_cal_usuario")
        self.radioButton_pto_cal_medidor = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_pto_cal_medidor.setGeometry(QtCore.QRect(20, 40, 131, 23))
        self.radioButton_pto_cal_medidor.setObjectName("radioButton_pto_cal_medidor")
        self.LOAD_CAL = QtWidgets.QPushButton(self.calibracion)
        self.LOAD_CAL.setGeometry(QtCore.QRect(340, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(10)
        self.LOAD_CAL.setFont(font)
        self.LOAD_CAL.setObjectName("LOAD_CAL")
        self.toolButton_load_2 = QtWidgets.QToolButton(self.calibracion)
        self.toolButton_load_2.setGeometry(QtCore.QRect(520, 250, 31, 21))
        self.toolButton_load_2.setObjectName("toolButton_load_2")
        self.load_path_2 = QtWidgets.QLineEdit(self.calibracion)
        self.load_path_2.setGeometry(QtCore.QRect(340, 280, 211, 20))
        self.load_path_2.setReadOnly(False)
        self.load_path_2.setObjectName("load_path_2")
        self.save_path_2 = QtWidgets.QLineEdit(self.calibracion)
        self.save_path_2.setGeometry(QtCore.QRect(340, 200, 211, 21))
        self.save_path_2.setObjectName("save_path_2")
        self.toolButton_save_2 = QtWidgets.QToolButton(self.calibracion)
        self.toolButton_save_2.setGeometry(QtCore.QRect(520, 170, 31, 21))
        self.toolButton_save_2.setObjectName("toolButton_save_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.calibracion)
        self.textBrowser_2.setGeometry(QtCore.QRect(650, 50, 521, 471))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.groupBox_14 = QtWidgets.QGroupBox(self.calibracion)
        self.groupBox_14.setGeometry(QtCore.QRect(60, 370, 431, 381))
        self.groupBox_14.setAutoFillBackground(False)
        self.groupBox_14.setObjectName("groupBox_14")
        self.f_inicial_2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.f_inicial_2.setGeometry(QtCore.QRect(130, 50, 71, 20))
        self.f_inicial_2.setReadOnly(False)
        self.f_inicial_2.setObjectName("f_inicial_2")
        self.n_puntos_2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.n_puntos_2.setGeometry(QtCore.QRect(130, 100, 71, 20))
        self.n_puntos_2.setReadOnly(False)
        self.n_puntos_2.setObjectName("n_puntos_2")
        self.label_45 = QtWidgets.QLabel(self.groupBox_14)
        self.label_45.setGeometry(QtCore.QRect(20, 90, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_47 = QtWidgets.QLabel(self.groupBox_14)
        self.label_47.setGeometry(QtCore.QRect(20, 50, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_14)
        self.label_48.setGeometry(QtCore.QRect(240, 50, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.f_final_2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.f_final_2.setGeometry(QtCore.QRect(330, 50, 71, 20))
        self.f_final_2.setReadOnly(False)
        self.f_final_2.setObjectName("f_final_2")
        self.label_49 = QtWidgets.QLabel(self.groupBox_14)
        self.label_49.setGeometry(QtCore.QRect(240, 90, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.ancho_banda_2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.ancho_banda_2.setGeometry(QtCore.QRect(330, 100, 71, 20))
        self.ancho_banda_2.setReadOnly(False)
        self.ancho_banda_2.setObjectName("ancho_banda_2")
        self.label_54 = QtWidgets.QLabel(self.groupBox_14)
        self.label_54.setGeometry(QtCore.QRect(40, 110, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.groupBox_14)
        self.label_55.setGeometry(QtCore.QRect(260, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_14)
        self.label_56.setGeometry(QtCore.QRect(40, 184, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_14)
        self.label_57.setGeometry(QtCore.QRect(20, 164, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.vosc_2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.vosc_2.setGeometry(QtCore.QRect(130, 170, 71, 20))
        self.vosc_2.setReadOnly(False)
        self.vosc_2.setObjectName("vosc_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_8.setGeometry(QtCore.QRect(240, 150, 161, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton_lineal_2 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_lineal_2.setGeometry(QtCore.QRect(20, 27, 111, 23))
        self.radioButton_lineal_2.setObjectName("radioButton_lineal_2")
        self.radioButton_log_2 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_log_2.setGeometry(QtCore.QRect(20, 50, 111, 23))
        self.radioButton_log_2.setObjectName("radioButton_log_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 240, 171, 131))
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_DC_OFF_2 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_DC_OFF_2.setGeometry(QtCore.QRect(20, 50, 111, 23))
        self.radioButton_DC_OFF_2.setObjectName("radioButton_DC_OFF_2")
        self.radioButton_DC_ON_2 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_DC_ON_2.setGeometry(QtCore.QRect(20, 27, 111, 23))
        self.radioButton_DC_ON_2.setObjectName("radioButton_DC_ON_2")
        self.label_21 = QtWidgets.QLabel(self.groupBox_9)
        self.label_21.setGeometry(QtCore.QRect(10, 76, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.nivel_DC_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.nivel_DC_2.setGeometry(QtCore.QRect(40, 100, 71, 20))
        self.nivel_DC_2.setReadOnly(False)
        self.nivel_DC_2.setObjectName("nivel_DC_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_7.setGeometry(QtCore.QRect(220, 250, 181, 121))
        self.groupBox_7.setObjectName("groupBox_7")
        self.avg_2 = QtWidgets.QCheckBox(self.groupBox_7)
        self.avg_2.setGeometry(QtCore.QRect(10, 30, 92, 23))
        self.avg_2.setObjectName("avg_2")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(10, 60, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.n_medidas_punto_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.n_medidas_punto_2.setGeometry(QtCore.QRect(50, 90, 71, 20))
        self.n_medidas_punto_2.setReadOnly(False)
        self.n_medidas_punto_2.setObjectName("n_medidas_punto_2")
        self.tabWidget.addTab(self.calibracion, "")
        self.fit = QtWidgets.QWidget()
        self.fit.setObjectName("fit")
        self.frame_5 = QtWidgets.QFrame(self.fit)
        self.frame_5.setGeometry(QtCore.QRect(0, 10, 1261, 511))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 921, 481))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.mpl_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.mpl_3.setContentsMargins(0, 0, 0, 0)
        self.mpl_3.setObjectName("mpl_3")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(310, 0, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.AJUSTA = QtWidgets.QPushButton(self.frame_5)
        self.AJUSTA.setGeometry(QtCore.QRect(970, 250, 161, 21))
        self.AJUSTA.setObjectName("AJUSTA")
        self.groupBox_16 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_16.setGeometry(QtCore.QRect(960, 280, 271, 151))
        self.groupBox_16.setObjectName("groupBox_16")
        self.comboBox_mag_fit = QtWidgets.QComboBox(self.groupBox_16)
        self.comboBox_mag_fit.setGeometry(QtCore.QRect(10, 57, 71, 21))
        self.comboBox_mag_fit.setMaxVisibleItems(6)
        self.comboBox_mag_fit.setObjectName("comboBox_mag_fit")
        self.n_func = QtWidgets.QLineEdit(self.groupBox_16)
        self.n_func.setGeometry(QtCore.QRect(180, 57, 71, 20))
        self.n_func.setReadOnly(False)
        self.n_func.setObjectName("n_func")
        self.label_35 = QtWidgets.QLabel(self.groupBox_16)
        self.label_35.setGeometry(QtCore.QRect(90, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_31 = QtWidgets.QLabel(self.groupBox_16)
        self.label_31.setGeometry(QtCore.QRect(170, 29, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_22 = QtWidgets.QLabel(self.groupBox_16)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.comboBox_fit_alg = QtWidgets.QComboBox(self.groupBox_16)
        self.comboBox_fit_alg.setGeometry(QtCore.QRect(90, 57, 71, 21))
        self.comboBox_fit_alg.setObjectName("comboBox_fit_alg")
        self.label_27 = QtWidgets.QLabel(self.groupBox_16)
        self.label_27.setGeometry(QtCore.QRect(10, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.f_high = QtWidgets.QLineEdit(self.groupBox_16)
        self.f_high.setGeometry(QtCore.QRect(150, 120, 111, 20))
        self.f_high.setReadOnly(False)
        self.f_high.setObjectName("f_high")
        self.f_low = QtWidgets.QLineEdit(self.groupBox_16)
        self.f_low.setGeometry(QtCore.QRect(10, 120, 111, 20))
        self.f_low.setReadOnly(False)
        self.f_low.setObjectName("f_low")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(970, 440, 251, 51))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("ecuacion_gompertz.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_10.setGeometry(QtCore.QRect(960, 150, 271, 91))
        self.groupBox_10.setObjectName("groupBox_10")
        self.load_path_3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.load_path_3.setGeometry(QtCore.QRect(10, 30, 211, 20))
        self.load_path_3.setReadOnly(False)
        self.load_path_3.setObjectName("load_path_3")
        self.LOAD_fit_data = QtWidgets.QPushButton(self.groupBox_10)
        self.LOAD_fit_data.setGeometry(QtCore.QRect(10, 60, 161, 21))
        self.LOAD_fit_data.setObjectName("LOAD_fit_data")
        self.toolButton_load_3 = QtWidgets.QToolButton(self.groupBox_10)
        self.toolButton_load_3.setGeometry(QtCore.QRect(230, 30, 31, 21))
        self.toolButton_load_3.setObjectName("toolButton_load_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_17.setGeometry(QtCore.QRect(960, 10, 271, 131))
        self.groupBox_17.setObjectName("groupBox_17")
        self.load_path_4 = QtWidgets.QLineEdit(self.groupBox_17)
        self.load_path_4.setGeometry(QtCore.QRect(10, 30, 211, 20))
        self.load_path_4.setReadOnly(False)
        self.load_path_4.setObjectName("load_path_4")
        self.toolButton_load_4 = QtWidgets.QToolButton(self.groupBox_17)
        self.toolButton_load_4.setGeometry(QtCore.QRect(230, 30, 31, 21))
        self.toolButton_load_4.setObjectName("toolButton_load_4")
        self.spinBox_pollo = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_pollo.setGeometry(QtCore.QRect(80, 60, 44, 26))
        self.spinBox_pollo.setObjectName("spinBox_pollo")
        self.label_8 = QtWidgets.QLabel(self.groupBox_17)
        self.label_8.setGeometry(QtCore.QRect(20, 60, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_17)
        self.label_9.setGeometry(QtCore.QRect(150, 60, 67, 17))
        self.label_9.setObjectName("label_9")
        self.spinBox_medida = QtWidgets.QSpinBox(self.groupBox_17)
        self.spinBox_medida.setGeometry(QtCore.QRect(220, 60, 44, 26))
        self.spinBox_medida.setObjectName("spinBox_medida")
        self.LOAD_fit_data_2 = QtWidgets.QPushButton(self.groupBox_17)
        self.LOAD_fit_data_2.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.LOAD_fit_data_2.setObjectName("LOAD_fit_data_2")
        self.SAVE_fit = QtWidgets.QPushButton(self.groupBox_17)
        self.SAVE_fit.setGeometry(QtCore.QRect(156, 100, 111, 21))
        self.SAVE_fit.setObjectName("SAVE_fit")
        self.groupBox_11 = QtWidgets.QGroupBox(self.fit)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 670, 241, 121))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_24 = QtWidgets.QLabel(self.groupBox_11)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.param_B1 = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_B1.setGeometry(QtCore.QRect(100, 30, 61, 20))
        self.param_B1.setReadOnly(False)
        self.param_B1.setObjectName("param_B1")
        self.label_25 = QtWidgets.QLabel(self.groupBox_11)
        self.label_25.setGeometry(QtCore.QRect(10, 60, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.param_C1 = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_C1.setGeometry(QtCore.QRect(100, 60, 61, 20))
        self.param_C1.setReadOnly(False)
        self.param_C1.setObjectName("param_C1")
        self.param_D1 = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_D1.setGeometry(QtCore.QRect(100, 90, 61, 20))
        self.param_D1.setReadOnly(False)
        self.param_D1.setObjectName("param_D1")
        self.label_26 = QtWidgets.QLabel(self.groupBox_11)
        self.label_26.setGeometry(QtCore.QRect(10, 90, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.param_C1_L = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_C1_L.setGeometry(QtCore.QRect(30, 60, 61, 20))
        self.param_C1_L.setReadOnly(False)
        self.param_C1_L.setObjectName("param_C1_L")
        self.param_D1_L = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_D1_L.setGeometry(QtCore.QRect(30, 90, 61, 20))
        self.param_D1_L.setReadOnly(False)
        self.param_D1_L.setObjectName("param_D1_L")
        self.param_B1_L = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_B1_L.setGeometry(QtCore.QRect(30, 30, 61, 20))
        self.param_B1_L.setReadOnly(False)
        self.param_B1_L.setObjectName("param_B1_L")
        self.param_B1_H = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_B1_H.setGeometry(QtCore.QRect(170, 30, 61, 20))
        self.param_B1_H.setReadOnly(False)
        self.param_B1_H.setObjectName("param_B1_H")
        self.param_D1_H = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_D1_H.setGeometry(QtCore.QRect(170, 90, 61, 20))
        self.param_D1_H.setReadOnly(False)
        self.param_D1_H.setObjectName("param_D1_H")
        self.param_C1_H = QtWidgets.QLineEdit(self.groupBox_11)
        self.param_C1_H.setGeometry(QtCore.QRect(170, 60, 61, 20))
        self.param_C1_H.setReadOnly(False)
        self.param_C1_H.setObjectName("param_C1_H")
        self.groupBox_15 = QtWidgets.QGroupBox(self.fit)
        self.groupBox_15.setGeometry(QtCore.QRect(310, 670, 241, 121))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_32 = QtWidgets.QLabel(self.groupBox_15)
        self.label_32.setGeometry(QtCore.QRect(10, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.param_B3 = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_B3.setGeometry(QtCore.QRect(100, 30, 61, 20))
        self.param_B3.setReadOnly(False)
        self.param_B3.setObjectName("param_B3")
        self.label_33 = QtWidgets.QLabel(self.groupBox_15)
        self.label_33.setGeometry(QtCore.QRect(10, 60, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.param_C3 = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_C3.setGeometry(QtCore.QRect(100, 60, 61, 20))
        self.param_C3.setReadOnly(False)
        self.param_C3.setObjectName("param_C3")
        self.param_D3 = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_D3.setGeometry(QtCore.QRect(100, 90, 61, 20))
        self.param_D3.setReadOnly(False)
        self.param_D3.setObjectName("param_D3")
        self.label_34 = QtWidgets.QLabel(self.groupBox_15)
        self.label_34.setGeometry(QtCore.QRect(10, 90, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.param_B3_L = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_B3_L.setGeometry(QtCore.QRect(30, 30, 61, 20))
        self.param_B3_L.setReadOnly(False)
        self.param_B3_L.setObjectName("param_B3_L")
        self.param_B3_H = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_B3_H.setGeometry(QtCore.QRect(170, 30, 61, 20))
        self.param_B3_H.setReadOnly(False)
        self.param_B3_H.setObjectName("param_B3_H")
        self.param_C3_H = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_C3_H.setGeometry(QtCore.QRect(170, 60, 61, 20))
        self.param_C3_H.setReadOnly(False)
        self.param_C3_H.setObjectName("param_C3_H")
        self.param_C3_L = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_C3_L.setGeometry(QtCore.QRect(30, 60, 61, 20))
        self.param_C3_L.setReadOnly(False)
        self.param_C3_L.setObjectName("param_C3_L")
        self.param_D3_H = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_D3_H.setGeometry(QtCore.QRect(170, 90, 61, 20))
        self.param_D3_H.setReadOnly(False)
        self.param_D3_H.setObjectName("param_D3_H")
        self.param_D3_L = QtWidgets.QLineEdit(self.groupBox_15)
        self.param_D3_L.setGeometry(QtCore.QRect(30, 90, 61, 20))
        self.param_D3_L.setReadOnly(False)
        self.param_D3_L.setObjectName("param_D3_L")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.fit)
        self.textBrowser_3.setGeometry(QtCore.QRect(580, 530, 681, 271))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_6 = QtWidgets.QLabel(self.fit)
        self.label_6.setGeometry(QtCore.QRect(40, 540, 231, 41))
        self.label_6.setObjectName("label_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.fit)
        self.groupBox_12.setGeometry(QtCore.QRect(310, 530, 241, 121))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_28 = QtWidgets.QLabel(self.groupBox_12)
        self.label_28.setGeometry(QtCore.QRect(10, 30, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.param_B2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_B2.setGeometry(QtCore.QRect(100, 30, 61, 20))
        self.param_B2.setReadOnly(False)
        self.param_B2.setObjectName("param_B2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_12)
        self.label_29.setGeometry(QtCore.QRect(10, 60, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.param_C2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_C2.setGeometry(QtCore.QRect(100, 60, 61, 20))
        self.param_C2.setReadOnly(False)
        self.param_C2.setObjectName("param_C2")
        self.param_D2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_D2.setGeometry(QtCore.QRect(100, 90, 61, 20))
        self.param_D2.setReadOnly(False)
        self.param_D2.setObjectName("param_D2")
        self.label_30 = QtWidgets.QLabel(self.groupBox_12)
        self.label_30.setGeometry(QtCore.QRect(10, 90, 21, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.param_C2_L = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_C2_L.setGeometry(QtCore.QRect(30, 60, 61, 20))
        self.param_C2_L.setReadOnly(False)
        self.param_C2_L.setObjectName("param_C2_L")
        self.param_B2_L = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_B2_L.setGeometry(QtCore.QRect(30, 30, 61, 20))
        self.param_B2_L.setReadOnly(False)
        self.param_B2_L.setObjectName("param_B2_L")
        self.param_D2_L = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_D2_L.setGeometry(QtCore.QRect(30, 90, 61, 20))
        self.param_D2_L.setReadOnly(False)
        self.param_D2_L.setObjectName("param_D2_L")
        self.param_B2_H = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_B2_H.setGeometry(QtCore.QRect(170, 30, 61, 20))
        self.param_B2_H.setReadOnly(False)
        self.param_B2_H.setObjectName("param_B2_H")
        self.param_D2_H = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_D2_H.setGeometry(QtCore.QRect(170, 90, 61, 20))
        self.param_D2_H.setReadOnly(False)
        self.param_D2_H.setObjectName("param_D2_H")
        self.param_C2_H = QtWidgets.QLineEdit(self.groupBox_12)
        self.param_C2_H.setGeometry(QtCore.QRect(170, 60, 61, 20))
        self.param_C2_H.setReadOnly(False)
        self.param_C2_H.setObjectName("param_C2_H")
        self.label_23 = QtWidgets.QLabel(self.fit)
        self.label_23.setGeometry(QtCore.QRect(40, 610, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.param_A1 = QtWidgets.QLineEdit(self.fit)
        self.param_A1.setGeometry(QtCore.QRect(130, 610, 61, 20))
        self.param_A1.setReadOnly(False)
        self.param_A1.setObjectName("param_A1")
        self.param_A1_H = QtWidgets.QLineEdit(self.fit)
        self.param_A1_H.setGeometry(QtCore.QRect(200, 610, 61, 20))
        self.param_A1_H.setReadOnly(False)
        self.param_A1_H.setObjectName("param_A1_H")
        self.param_A1_L = QtWidgets.QLineEdit(self.fit)
        self.param_A1_L.setGeometry(QtCore.QRect(60, 610, 61, 20))
        self.param_A1_L.setReadOnly(False)
        self.param_A1_L.setObjectName("param_A1_L")
        self.tabWidget.addTab(self.fit, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_13.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interfaz 4294A"))
        self.label_4.setText(_translate("MainWindow", "ANÁLISIS DE DATOS"))
        self.label_3.setText(_translate("MainWindow", "DATOS MEDIDOS"))
        self.label.setText(_translate("MainWindow", "CONTROL REMOTO REDPITAYA"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Configuración de Medida"))
        self.label_42.setText(_translate("MainWindow", "Número Puntos"))
        self.label_44.setText(_translate("MainWindow", "Freq. Inicial"))
        self.label_46.setText(_translate("MainWindow", "Freq. Final"))
        self.label_43.setText(_translate("MainWindow", "R shunt"))
        self.label_50.setText(_translate("MainWindow", "[1-801]"))
        self.label_51.setText(_translate("MainWindow", "[0-5]"))
        self.label_52.setText(_translate("MainWindow", "[0-1V]"))
        self.label_53.setText(_translate("MainWindow", "V. Oscilador"))
        self.groupBox.setTitle(_translate("MainWindow", "Tipo Barrido"))
        self.radioButton_lineal.setText(_translate("MainWindow", "Lineal"))
        self.radioButton_log.setText(_translate("MainWindow", "Logarítmico"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Configuración BIAS"))
        self.radioButton_DC_OFF.setText(_translate("MainWindow", "DC bias OFF"))
        self.radioButton_DC_ON.setText(_translate("MainWindow", "DC bias ON"))
        self.label_15.setText(_translate("MainWindow", "Nivel DC [-40V,40V]"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Postprocesado"))
        self.radioButton.setText(_translate("MainWindow", "FFT"))
        self.radioButton_2.setText(_translate("MainWindow", "Correlación"))
        self.MEDIR.setText(_translate("MainWindow", "MEDIR"))
        self.groupBox_2.setTitle(_translate("MainWindow", "PLOT"))
        self.label_16.setText(_translate("MainWindow", "EJE Y - (ROJO)"))
        self.label_17.setText(_translate("MainWindow", "EJE Y - (AZUL)"))
        self.REDRAW_MEASURE.setText(_translate("MainWindow", "REDIBUJAR\n"
"MEDIDA"))
        self.groupBox_18.setTitle(_translate("MainWindow", "FICHERO CSV"))
        self.LOAD_M.setText(_translate("MainWindow", "CARGAR/REDIBUJAR DATOS - CSV"))
        self.toolButton_load.setText(_translate("MainWindow", "..."))
        self.SAVE_M.setText(_translate("MainWindow", "GUARDAR MEDIDA - CSV"))
        self.toolButton_save.setText(_translate("MainWindow", "..."))
        self.SAVE_cfg.setText(_translate("MainWindow", "SALVAR CONFIG."))
        self.SAVE_DB.setText(_translate("MainWindow", "SALVAR \n"
" BASE DE DATOS"))
        self.toolButton_load_db.setText(_translate("MainWindow", "..."))
        self.label_36.setText(_translate("MainWindow", "BASE DE DATOS"))
        self.label_37.setText(_translate("MainWindow", "ÚLTIMO POLLO"))
        self.label_38.setText(_translate("MainWindow", "ÚLTIMA MEDIDA"))
        self.label_39.setText(_translate("MainWindow", "POLLO"))
        self.label_40.setText(_translate("MainWindow", "MEDIDA"))
        self.label_41.setText(_translate("MainWindow", "ESTADO DEL POLLO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.datos), _translate("MainWindow", "SENSOR PECTORAL"))
        self.GO_CAL.setText(_translate("MainWindow", "COMENZAR \n"
" CALIBRACIÓN"))
        self.SAVE_CAL.setText(_translate("MainWindow", "Guardar Calibración"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Configuración Calibración"))
        self.radioButton_config_cal_2.setText(_translate("MainWindow", "Abierto, Corto"))
        self.radioButton_config_cal_1.setText(_translate("MainWindow", "Carga, Abierto, Corto"))
        self.label_18.setText(_translate("MainWindow", "C Load (fF)"))
        self.label_19.setText(_translate("MainWindow", "G Load (S)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Puntos de Calibración"))
        self.radioButton_pto_cal_usuario.setText(_translate("MainWindow", "Usuario"))
        self.radioButton_pto_cal_medidor.setText(_translate("MainWindow", "Medidor"))
        self.LOAD_CAL.setText(_translate("MainWindow", "Cargar Calibración"))
        self.toolButton_load_2.setText(_translate("MainWindow", "..."))
        self.toolButton_save_2.setText(_translate("MainWindow", "..."))
        self.groupBox_14.setTitle(_translate("MainWindow", "Configuración de la Calibración"))
        self.label_45.setText(_translate("MainWindow", "Número Puntos"))
        self.label_47.setText(_translate("MainWindow", "Freq. Inicial"))
        self.label_48.setText(_translate("MainWindow", "Freq. Final"))
        self.label_49.setText(_translate("MainWindow", "Ancho Banda"))
        self.label_54.setText(_translate("MainWindow", "[1-801]"))
        self.label_55.setText(_translate("MainWindow", "[1-5]"))
        self.label_56.setText(_translate("MainWindow", "[0-1V]"))
        self.label_57.setText(_translate("MainWindow", "V. Oscilador"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Tipo Barrido"))
        self.radioButton_lineal_2.setText(_translate("MainWindow", "Lineal"))
        self.radioButton_log_2.setText(_translate("MainWindow", "Logarítmico"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Configuración BIAS"))
        self.radioButton_DC_OFF_2.setText(_translate("MainWindow", "DC bias OFF"))
        self.radioButton_DC_ON_2.setText(_translate("MainWindow", "DC bias ON"))
        self.label_21.setText(_translate("MainWindow", "Nivel DC [-40V,40V]"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Promediado"))
        self.avg_2.setText(_translate("MainWindow", "Activar"))
        self.label_20.setText(_translate("MainWindow", "Medidas/pto [1-256]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibracion), _translate("MainWindow", "CALIBRACIÓN"))
        self.label_5.setText(_translate("MainWindow", "AJUSTE DE GOMPERTZ"))
        self.AJUSTA.setText(_translate("MainWindow", "AJUSTA MEDIDA"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Ajuste"))
        self.label_35.setText(_translate("MainWindow", "Método "))
        self.label_31.setText(_translate("MainWindow", "Num funciones"))
        self.label_22.setText(_translate("MainWindow", "Magnitud "))
        self.label_27.setText(_translate("MainWindow", "Rango frecuencias"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Datos desde Fichero CSV"))
        self.LOAD_fit_data.setText(_translate("MainWindow", "AJUSTA DATOS CSV"))
        self.toolButton_load_3.setText(_translate("MainWindow", "..."))
        self.groupBox_17.setTitle(_translate("MainWindow", "Datos desde Base de Datos HDF5"))
        self.toolButton_load_4.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Pollo"))
        self.label_9.setText(_translate("MainWindow", "Medida"))
        self.LOAD_fit_data_2.setText(_translate("MainWindow", "AJUSTA BASE DATOS"))
        self.SAVE_fit.setText(_translate("MainWindow", "SALVA AJUSTE"))
        self.groupBox_11.setTitle(_translate("MainWindow", "GOMPERTZ 1"))
        self.label_24.setText(_translate("MainWindow", "B"))
        self.label_25.setText(_translate("MainWindow", "C"))
        self.label_26.setText(_translate("MainWindow", "D"))
        self.groupBox_15.setTitle(_translate("MainWindow", "GOMPERTZ 3"))
        self.label_32.setText(_translate("MainWindow", "B"))
        self.label_33.setText(_translate("MainWindow", "C"))
        self.label_34.setText(_translate("MainWindow", "D"))
        self.label_6.setText(_translate("MainWindow", "VALORES INICIALES y LIMITES"))
        self.groupBox_12.setTitle(_translate("MainWindow", "GOMPERTZ 2"))
        self.label_28.setText(_translate("MainWindow", "B"))
        self.label_29.setText(_translate("MainWindow", "C"))
        self.label_30.setText(_translate("MainWindow", "D"))
        self.label_23.setText(_translate("MainWindow", "A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fit), _translate("MainWindow", "AJUSTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

